apiVersion: v2
name: harperdb
description: "HarperDB is a turn-key solution for the collection, distribution, and analysis of data."
type: application
version: 0.2.3
appVersion: "4.1.3"
keywords:
  - harperdb
  - database
home: https://harperdb.io
maintainers:
  - name: harperdb support
    emai: support@harperdb.io

annotations:
  # artifactHub.io annotations (https://artifacthub.io/docs/topics/annotations/helm/}
  artifacthub.io/category: database