apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harperdb.fullname" . }}
  {{- with (merge (.Values.extraLabels | default dict) (include "harperdb.labels" $ | fromYaml)) }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  CLUSTERING_ENABLED: "{{ .Values.clustering.enabled }}"
  CLUSTERING_NODENAME: "{{ .Values.clustering.nodeName | default (include "harperdb.fullname" .) }}"
  CUSTOMFUNCTIONS_ENABLED: "{{ .Values.componentApiEnabled }}"
  CUSTOMFUNCTIONS_NETWORK_HTTPS: "{{ .Values.componentApiHttps }}"
  HTTP_THREADS: "{{ .Values.threads }}"
  OPERATIONSAPI_NETWORK_HTTPS: "{{ .Values.operationsApiHttps }}"
  ROOTPATH: "{{ .Values.persistentStorage.mountPath }}"
  {{- with .Values.configMapExtraEnv }}
  {{- toYaml . | nindent 2 }}
  {{- end }}