{{- if or (empty .Values.existingSecretRef) (and (.Values.clustering.enabled) (empty .Values.clustering.existingSecretRef))  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harperdb.fullname" . }}
  {{- with (merge (.Values.extraLabels | default dict) (include "harperdb.labels" $ | fromYaml)) }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- if empty .Values.existingSecretRef }}
  HDB_ADMIN_USERNAME: {{ include "harperdb.secrets.username" . | trim | b64enc }}
  HDB_ADMIN_PASSWORD: {{ include "harperdb.secrets.password" . | trim | b64enc }}
  {{- end }}
  {{- if and (.Values.clustering.enabled) (empty .Values.clustering.existingSecretRef) }}
  CLUSTERING_USER: {{ include "harperdb.secrets.clustering.username" . | trim | b64enc }}
  CLUSTERING_PASSWORD: {{ include "harperdb.secrets.clustering.password" . | trim | b64enc }}
  {{- end }}
{{- end }}