apiVersion: v1
kind: Service
metadata:
  name: {{ include "harperdb.fullname" . }}
  labels:
    {{- include "harperdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.operationsPort }}
      targetPort: operations
      protocol: TCP
      name: operations
    {{- if .Values.componentApiEnabled }}
    - port: {{ .Values.service.componentPort }}
      targetPort: component
      protocol: TCP
      name: component
    {{- end }}
    {{- if .Values.clustering.enabled }}
    - port: {{ .Values.service.clusteringPort }}
      targetPort: clustering
      protocol: TCP
      name: clustering
    {{- end }}
  selector:
    {{- include "harperdb.selectorLabels" . | nindent 4 }}
